# ═══════════════════════════════════════════════════════════
# schedule-hidden.ps1 — 註冊排程（隱藏視窗版）
# ═══════════════════════════════════════════════════════════
#
# 功能：
#   把 1_poetry-demo.ps1 註冊到 Windows Task Scheduler，
#   設定在「當下時間 + 30 秒」自動觸發一次。
#   執行時完全靜默，畫面不會彈出任何視窗。
#   體驗「真正無感的自動化」。
#
# 使用方式：
#   1. 先確認 1_poetry-demo.ps1 與本腳本在同一個資料夾
#   2. 在 PowerShell 執行：
#        .\4_schedule-hidden.ps1
#   3. 等 30 秒，什麼視窗都不會出現，但資料夾會多出 3 個 poem md 檔
#   4. 清理：執行 .\5_unschedule-hidden.ps1
#
# 任務名稱：Kiro Poetry (Hidden)
#
# 與 schedule-with-window.ps1 的差異：
#   光靠 powershell.exe -WindowStyle Hidden 沒辦法真正藏住黑窗，
#   PowerShell 啟動那一瞬間還是會閃一下
#   （GitHub issue #3028 官方也承認這是已知行為）。
#
#   真正 100% 靜默的做法是用 wscript.exe 執行一支 VBS launcher，
#   由它在背景呼叫 PowerShell。因為 wscript 本身就不會建立 console
#   視窗，所以全程零閃爍。
#
# ═══════════════════════════════════════════════════════════

$taskName = "Kiro Poetry (Hidden)"
$scriptPath = Join-Path $PSScriptRoot "1_poetry-demo.ps1"
$workingDir = $PSScriptRoot
$triggerTime = (Get-Date).AddSeconds(30)

# 產生 VBS launcher：用 wscript 執行，WshShell.Run 的第二參數 0 代表隱藏
$vbsPath = Join-Path $PSScriptRoot "_hidden_launcher.vbs"
$vbsContent = @"
' Auto-generated by 4_schedule-hidden.ps1
' 用途：讓 Task Scheduler 呼叫本檔，由它在背景啟動 PowerShell
' 這樣可以完全避免 powershell.exe -WindowStyle Hidden 的黑窗閃爍
Set objShell = CreateObject("WScript.Shell")
objShell.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""$scriptPath""", 0, False
"@
Set-Content -Path $vbsPath -Value $vbsContent -Encoding Default

# 關鍵差異：不直接呼叫 powershell.exe，改由 wscript.exe 執行 VBS launcher
$action = New-ScheduledTaskAction `
    -Execute "wscript.exe" `
    -Argument "`"$vbsPath`"" `
    -WorkingDirectory $workingDir

$trigger = New-ScheduledTaskTrigger -Once -At $triggerTime

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10)

# 移除同名舊任務（若存在）
Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue

Register-ScheduledTask `
    -TaskName $taskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Description "Kiro Poetry demo — hidden terminal version (via VBS launcher)"

Write-Host ""
Write-Host "✅ 已註冊任務：$taskName" -ForegroundColor Green
Write-Host "   觸發時間：$($triggerTime.ToString('yyyy-MM-dd HH:mm:ss'))" -ForegroundColor Yellow
Write-Host "   Launcher：$vbsPath" -ForegroundColor Gray
Write-Host "   請等待約 30 秒，畫面不會有任何變化，但檔案會悄悄產生" -ForegroundColor Yellow
